### ISSUE TITLE
Naming convention for lifecycle functions

### ISSUE THREAD

**Issue by metametadata** [weavejester/integrant#7]
Not all the lifecycle functions end with an exclamation mark:

```
init
halt!
resume
suspend!
init-key
halt-key!
etc.
```

I'd expect all the lifecycle functions to have `!` (because they are all equally side-effectful/unsafe) or none at all (because I know I deal with stateful stuff when `ig/` functions are invoked).

**Comment by weavejester** [comment]
The convention I'm using is that all functions that end in a `!` are *purely* side-effectful and the return value should be ignored. Since all lifecycle functions are potentially side-effectful, adding an `!` to the end of all of them would be pointless, so in the context of Integrant I've adjusted the normal meaning.

**Comment by metametadata** [comment]
Aha, it wasn't obvious to me that naming is connected to ability to return values. I guess the issue can be closed then. Thanks!

**Comment by weavejester** [comment]
I'll make a note of it in the README.
